### ISSUE TITLE
No module named 'Data'

### ISSUE THREAD

**Issue by Mant1sss** [THECRAZEDPOTATTO/TikTok-share-botter#1]
Traceback (most recent call last):
  File "C:\Users\diplo\Desktop\TikTok-share-botter-main\main.py", line 7, in <module>
    from Data.UserAgent import UserAgent
ModuleNotFoundError: No module named 'Data'

[process exited with code 1 (0x00000001)]

**Comment by THECRAZEDPOTATTO** [comment]
> Traceback (most recent call last):
> 
>   File "C:\Users\diplo\Desktop\TikTok-share-botter-main\main.py", line 7, in <module>
> 
>     from Data.UserAgent import UserAgent
> 
> ModuleNotFoundError: No module named 'Data'
> 
> 
> 
> [process exited with code 1 (0x00000001)]

Fixed
